### PR TITLE
Update Mac Chrome Plugin for latest Chrome versions

### PR DESCRIPTION
**Pull request by steven-king**
Great work, love the project! 
I am submitting code that makes the chrome plugin/extension work with the latest version of Chrome. There are several deprecated methods and other changes need to allow the extension  to install without errors. 
It has been tested on Mac Chrome Version 22.0.1229.94.

Changes:

changed chrome.extension.sendRequest to chrome.extensions.SendMessage
in chrome.js

Removed inline scripts in background.html and created initPlugin.js

added popup.html file from previous version and updated .sendMessage
Moved inlinescript from popup.html

Updated manifest to verson 2 and replaced background_page with
background.html and popup to default_popup

### CODE REVIEW

**Comment by tan-c** [comment]
hey thanks for the code man. but i am having this problem with background.html. 

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource: (background.html:1)

However, apparently there were not any inline script in the new html file. (there was one in the original background.html and from what i know manifest v2 disallow inline script), so i dont know what is the problem.

The popup box is showing, however both Connect to Kinect and Disconnect to Kinnect are disabled. and blob is not showing up on any window as well.

I am running Chrome Version 22.0.1229.94 on Mac 10.7.4.

Thanks!

**Comment by steven-king** [comment]
I am not sure why the inline script error comes up. I am also getting that now. I had not noticed it before but it works despite the error. 

I also have the connect/disconnect disabled in the popup but I am able to select the different modes which works. 

One thing that is not in the docs and I can't explain is that I can't get the demo or any other page working locally but it does work on a server. Test your plugin and Kinect here: http://steventking.com/gesture_interface_site/BasicDemo.html I just tested it and it is working with the plugin I uploaded and my Kinect. Also, http://steventking.com is working for simple links menus.

Hope this helps! Good luck.
Steven

**Comment by tan-c** [comment]
@steven-king 

Thanks for the reply. The problem that i have for now seems to be that the blob window cannot show up. I never really got it on any page but i assume that once you activate the plugin it should display the blob window as pop-up.

The kinect looks fine to me as the red light is up and the green light keep blinking. When i go to your page http://steventking.com/gesture_interface_site/BasicDemo.html it also shows that 

DepthJS + Kinect detected+!@
Hand not in view

However the kinect works fine when i use the samples in openNI. Any idea on why the blob is not showing up? Would really appreciate the help.

**Comment by thevinci** [comment]
I have the same problem.

**Comment by steverhoades** [comment]
Same problem, although I do not see a red light at all.

**Pull request merged**
